services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: client_app
    environment:
      - VIRTUAL_HOST=tenant1.website.com
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage:/var/www/storage
      - ./tests:/var/www/tests
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./artisan:/var/www/artisan
      - ./phpunit.xml:/var/www/phpunit.xml
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./postcss.config.js:/var/www/postcss.config.js
      - ./vite.config.js:/var/www/vite.config.js
      - ./tailwind.config.js:/var/www/tailwind.config.js
      - ./yarn.lock:/var/www/yarn.lock
      - ./packages:/var/packages
      - ./.env:/var/www/.env

    ports:
      - "80:80"
    networks:
      - client

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: client_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - client

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: client_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    ports:
      - "8081:80"
    networks:
      - client


networks:
  client:
      name: client
      driver: bridge
