<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Trial Balance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12px;
            line-height: 1.4;
        }
        
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .company-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        .report-info {
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 15px;
            background-color: #f9f9f9;
        }
        
        .info-row {
            margin-bottom: 8px;
        }
        
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        
        .ledger-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 11px;
        }
        
        .ledger-table th {
            background-color: #f0f0f0;
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        
        .ledger-table td {
            border: 1px solid #ddd;
            padding: 6px 8px;
        }
        
        .text-right {
            text-align: right;
        }
        
        .text-center {
            text-align: center;
        }
        
        .font-bold {
            font-weight: bold;
        }
        
        .totals-section {
            border-top: 2px solid #333;
            padding-top: 15px;
            margin-top: 20px;
        }
        
        .totals-table {
            width: 300px;
            margin-left: auto;
            border-collapse: collapse;
        }
        
        .totals-table td {
            padding: 5px 10px;
            border-bottom: 1px solid #ddd;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
        
        .page-break {
            page-break-after: always;
        }
        
        @media print {
            body { margin: 0; }
            .page-break { page-break-after: always; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">Your Company Name</div>
        <div class="report-title">Cash Flow Statement</div>
        <div style="font-size: 12px; color: #666;">Generated on {{ $generatedAt }}</div>
    </div>

    <div class="report-info">
        @if($selectedYear)
        <div class="info-row">
            <span class="info-label">Year:</span>
            <span>{{ $selectedYear->start_date->format('Y') }} - {{ $selectedYear->end_date->format('Y') }}</span>
        </div>
        @endif
    </div>
    <table class="ledger-table">
        <thead>
            <tr>
                <th style="width: 25%;">Account</th>
                <th style="width: 20%; text-align: right;">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (['operating' => $operatingCashFlows, 'investing' => $investingCashFlows, 'financing' => $financingCashFlows] as $type => $flows)
                
                <tr>
                    <td colspan="2">{{ ucfirst($type) }} Activities</td>
                </tr>
                @forelse ($flows as $flow)
                    <tr>
                        <td style="padding-left: 36px;">{{ $flow['description'] }}</td>
                        <td style="width: 20%; text-align: right;">{{ number_format($flow['amount'], 2) }}</td>
                    </tr>
                @empty
                    <tr class="row text-gray-500" colspan="2">No data</tr>
                @endforelse
                <tr>
                    <td colspan="1" class="text-right">
                        Total {{ $type }}
                    </td>
                    <td class="text-right">
                        {{ number_format(${"{$type}Total"}, 2) }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    

    <script type="text/php">
        if (isset($pdf)) {
            $text1 = "page {PAGE_NUM} / {PAGE_COUNT}";
            $text2 = "Report generated by: {{ auth()->user()->name ?? 'System' }}";
            $text3 = "Generated by Processton Abacus";
            $size = 6;
            $font = $fontMetrics->getFont("Verdana");
            $width1 = $fontMetrics->get_text_width($text1, $font, $size) / 2;
            $width2 = $fontMetrics->get_text_width($text2, $font, $size) / 2;
            $width3 = $fontMetrics->get_text_width($text3, $font, $size) / 2;
            $footerY = $pdf->get_height() - 12;

            $x = (($pdf->get_width() - $width3) / 2) - 32;


            $x2 = ($pdf->get_width() - $width2) - 78;


            $pdf->page_text(25, $footerY, $text1, $font, $size);
            $pdf->page_text($x2, $footerY, $text2, $font, $size);
            $pdf->page_text($x, $footerY, $text3, $font, $size);
        }
    </script>
</body>
</html>
