name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120  # Increase timeout for large builds

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for better performance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image efficiently
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --compress \
            --push \
            --platform linux/amd64,linux/arm64 \
            -t processton/client-core:latest \
            -t processton/client-core:8.3 .
